const data=[
["00 · Inicio","Bucles en Java","De PSeInt a Java mediante aprendizaje guiado.","<b>Repositorio obligatorio:</b> C01-BUCLES-JAVA<br><br>Crea dentro EJERCICIO-01 hasta EJERCICIO-10. Cada ejercicio es una isla independiente con Main.java y README.md."],
["01 · Mi primer bucle","Mi primer bucle","Comprende por qué necesitamos repetir.","<b>CONCEPTO NUEVO · FOR</b><br><br>Un for repite un bloque controlando un contador.<pre>for (int i = 1; i <= 5; i++) {\n  System.out.println(i);\n}</pre><b>PSeInt → Java:</b> inicio, final y avance representan la misma idea."],
["02 · Controla el recorrido","Controla el recorrido","Domina inicio, condición y cambio.","Sigue el contador vuelta a vuelta. Compara <code>i < 10</code> con <code>i <= 10</code>. Modifica el inicio y el final y predice el resultado antes de ejecutar."],
["03 · Avanza de otra manera","Avanza de otra manera","Cambia cómo evoluciona el contador.","<b>CONCEPTO NUEVO</b><pre>i++      // aumenta 1\ni += 2   // aumenta 2\ni--      // disminuye 1</pre>Construye secuencias y una cuenta atrás."],
["04 · Decide en cada vuelta","Decide en cada vuelta","Combina for con if.","<b>RECUPERAMOS · IF</b><pre>for (int i=1; i<=10; i++) {\n  if (i % 2 == 0) {\n    System.out.println(i);\n  }\n}</pre>El if se evalúa en cada iteración."],
["05 · Transfiere desde PSeInt","Transfiere desde PSeInt","Reconoce el algoritmo antes de escribir Java.","<b>PSeInt → Java</b><br><br>Localiza primero: valor inicial → final → cambio → acción. Después transforma el Para en for. No traduzcas palabras: transfiere la estructura."],
["06 · Repite mientras se cumpla","Repite mientras se cumpla","Aprende cuándo usar while.","<b>CONCEPTO NUEVO · WHILE</b><pre>while (condicion) {\n  instrucciones;\n}</pre>Úsalo cuando el final depende de una condición y no conocemos de antemano el número de vueltas."],
["07 · Evita el bucle infinito","Evita el bucle infinito","Detecta por qué un while puede no terminar.","Pregunta clave: <b>¿la variable de la condición puede cambiar hasta hacerla falsa?</b><pre>int numero=1;\nwhile(numero<=5){\n  System.out.println(numero);\n}</pre>Localiza y repara el error."],
["08 · Cuenta y acumula","Cuenta y acumula","Distingue contador y acumulador.","<b>CONTADOR</b>: registra cuántas veces ocurre algo.<br><b>ACUMULADOR</b>: conserva un total.<pre>int suma=0;\nfor(int i=1;i<=5;i++){\n  suma=suma+i;\n}</pre>"],
["09 · Recorre un array","Recorre un array","Usa i como posición del array.","<b>RECUPERAMOS ARRAYS</b><br>Las posiciones empiezan en 0.<pre>int[] notas={7,5,9,4,8};\nfor(int i=0;i<notas.length;i++){\n  System.out.println(notas[i]);\n}</pre>"],
["10 · Integra lo aprendido","Integra lo aprendido","Combina array, for, if y contador.","<b>RETO GUIADO</b><br><br>ARRAY → FOR → notas[i] → IF nota >= 5 → aprobados++.<br><br>No aparece ningún concepto nuevo: ahora transfieres y combinas."],
["Repaso final","Repaso final","Comprueba lo que has aprendido.","No es un examen. Repasa elección entre for/while, condiciones, incrementos, bucles infinitos, contadores, acumuladores y recorrido de arrays."]
];
let cur=+(localStorage.c01page||0),done=JSON.parse(localStorage.c01done||"[]");
const app=document.getElementById("app"),nav=document.getElementById("nav"),title=document.getElementById("title"),bar=document.getElementById("bar"),pct=document.getElementById("pct");
function render(){localStorage.c01page=cur;let p=data[cur];title.textContent=p[0];app.innerHTML='<article><section class="hero"><span class="label">CUADERNO DE APRENDIZAJE</span><h2>'+p[1]+'</h2><p>'+p[2]+'</p></section><div class="card">'+p[3]+'</div>'+(cur>0&&cur<11?'<div class="card"><span class="label">RUTA DE TRABAJO</span><h3>C01-BUCLES-JAVA/EJERCICIO-'+String(cur).padStart(2,"0")+'</h3><p>Trabaja en <b>Main.java</b>, completa <b>README.md</b> y termina con commit + push.</p></div><div class="card learn"><span class="label">HE APRENDIDO</span><p>✓ Comprendo el concepto protagonista.</p><p>✓ Puedo modificarlo y comprobar el resultado.</p><p><b>¿Podría explicarlo sin mirar el código?</b></p></div>':'')+'</article>';nav.innerHTML=data.map((x,i)=>'<button data-i="'+i+'" class="'+(i===cur?'active ':'')+(done.includes(i)?'done':'')+'">'+x[0]+'</button>').join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>{cur=+b.dataset.i;render()});let pc=Math.round(done.length/data.length*100);bar.style.width=pc+"%";pct.textContent=pc+"% completado";prev.disabled=cur===0;next.disabled=cur===data.length-1;scrollTo(0,0)}
prev.onclick=()=>{cur--;render()};next.onclick=()=>{cur++;render()};done.onclick=()=>{if(!done.includes(cur))done.push(cur);localStorage.c01done=JSON.stringify(done);render()};reset.onclick=()=>{if(confirm("¿Reiniciar el progreso?")){done=[];cur=0;localStorage.clear();render()}};menu.onclick=()=>document.querySelector("aside").classList.toggle("open");render();